name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ''  # Node.js 버전 설정

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Setup Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        AZURE_CLIENT_ID: ${{ secrets.83d768a3-e166-4e6e-8ee0-f5886cb554fc }}
        AZURE_CLIENT_SECRET: ${{ secrets.AsU8Q~KDg723cjcR03Pf5ya42qVxcff3iD7.5ayT }}
        AZURE_TENANT_ID: ${{ secrets.bee29138-c48d-48ef-8133-9a68070b7096 }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group ${{ secrets.rg-garlicBear }} \
          --name ${{ secrets.garlicBear-webapp }} \
          --src ./path/to/your/zipfile.zip
      env:
        