name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 배포를 실행합니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # 사용 중인 Node.js 버전

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Setup Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        azure-subscription: ${{ secrets.bfa39d86-1058-4824-8074-e9d283d6c321 }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group ${{ secrets.rg-garlicBear }} \
          --name ${{ secrets.garlicBear-webapp }} \
          --src ./path/to/your/zipfile.zip
      env:
        AZURE_CLIENT_ID: ${{ secrets.930de797-1bc0-4f83-8c26-16eebcc2b244 }}
        AZURE_CLIENT_SECRET: ${{ secrets.Md-8Q~2Z~Tp01f23wlF2X7h7Jk9ELfgLgPYo-dvf }}
        AZURE_TENANT_ID: ${{ secrets.bee29138-c48d-48ef-8133-9a68070b7096 }}